version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: blog-app
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/blogdb?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo-data:
