version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: blog-app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:${MONGO_DB_PORT}/${MONGO_DB_NAME}?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongo-data:
